In [1]:
!pip install stable_baselines3[extra]

!apt-get install swig
!pip install gymnasium[box2d]
!pip install gym
!pip install pygame


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 12.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 958.1/958.1 kB 33.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.0/184.0 kB 10.5 MB/s eta 0:00:00
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  swig4.0
Suggested packages:
  swig-doc swig-examples swig4.0-examples swig4.0-doc
The following NEW packages will be installed:
  swig swig4.0
0 upgraded, 2 newly installed, 0 to remove and 49 not upgraded.
Need to get 1,116 kB of archives.
After this operation, 5,542 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 swig4.0 amd64 4.0.2-1ubuntu1 [1,110 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 swig all 4.0.2-1ubuntu1 [5,632 B]
Fetched 1,116 kB in 2s (481 kB/s)
Selecting previously unselected package swig4.0.
(Reading database ...

In [2]:
import gymnasium as gym
import numpy as np
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
import os

In [3]:
env=gym.make('CarRacing-v3')

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.11/dist-packages/pygame/pkgdata.py:25: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import resource_stream, resource_exists
/usr/local/lib/python3.11/dist-packages/pkg_resources/__init__.py:3154: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim
import random
from collections import deque
from stable_baselines3.common.vec_env import DummyVecEnv

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [5]:
!pip install shimmy

In [12]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

NUM_ENVS=4
env=DummyVecEnv([lambda: gym.make('CarRacing-v3') for _ in range(NUM_ENVS)])

print(f'using {device}')



Using device: cuda
using cuda


In [13]:
state_size=env.observation_space.shape
state_size

(96, 96, 3)

In [14]:
action_size=env.action_space
action_size


# Print action space details
print("Action Space:", env.action_space)
print("Action Space Shape:", env.action_space.shape)
print("Action Space High (Max):", env.action_space.high)
print("Action Space Low (Min):", env.action_space.low)


Action Space: Box([-1.  0.  0.], 1.0, (3,), float32)
Action Space Shape: (3,)
Action Space High (Max): [1. 1. 1.]
Action Space Low (Min): [-1.  0.  0.]


In [15]:
result = env.reset()
print(f"Type of result: {type(result)}, Result: {result}")


Type of result: <class 'numpy.ndarray'>, Result: [[[[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  ...

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]]


 [[[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  ...

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]]


 [[[0 0 0]
   [0 0 0]
   [0 0 0]


In [17]:

LEARNING_RATE = 0.001
DISCOUNT = 0.99
EPSILON = 1.0
EPSILON_DECAY = 0.995
EPSILON_MIN = 0.05
MEMORY_SIZE = 100000
BATCH_SIZE = 64
TARGET_UPDATE_FREQ = 1000
TOTAL_TIMESTEPS = 500000
TRAINING_START = 10000

class ReplayBuffer:
  def __init__(self,size):
    self.buffer=deque(maxlen=size)
  def add(self,experience):
    self.buffer.append(experience)
  def sample(self, batch_size):
    batch=random.sample(self.buffer, batch_size)
    states, actions,rewards,next_states,dones=zip(*batch)
    return (
        torch.tensor(np.array(states), dtype=torch.float32, device=device),
        torch.tensor(np.array(actions),dtype=torch.float32,device=device),
        torch.tensor(rewards, dtype=torch.float32, device=device),
        torch.tensor(np.array(next_states), dtype=torch.float32, device=device),
        torch.tensor(np.array(dones), dtype=torch.float32, device=device),
    )
  def can_sample(self, batch_size):
    return len(self.buffer)>=batch_size

memory= ReplayBuffer(MEMORY_SIZE)


#Q-network
class DQN(nn.Module):
    def __init__(self, state_size, action_size):
        super().__init__()
        self.network = nn.Sequential(
            # Convolutional layers
            #output size=(Input Size-Kernel Size+2xPadding)/Stride + 1
            nn.Conv2d(in_channels=3, out_channels=32, kernel_size=5, stride=2, padding=2), # Output: 48x48x32
            nn.ReLU(),
            nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, stride=2, padding=1), # Output: 24x24x64
            nn.ReLU(),
            nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, stride=2, padding=1), # Output: 12x12x128
            nn.ReLU(),
            nn.BatchNorm2d(128),


            nn.MaxPool2d(kernel_size=3, stride=2, padding=1), # Output: 6x6x128

            # Flattening the output for fully connected layers
            nn.Flatten(),

            # Fully connected layers
            nn.Linear(6 * 6 * 128, 512),  # Flattened output size is 6x6x128
            nn.ReLU(),
            nn.Linear(512, 3)  # Output layer for Q-values
        )

    def forward(self,x):
      x=self.network(x)
      steering=torch.tanh(x[:,0])
      accceleartion=torch.sigmoid(x[:,1])
      brake=torch.sigmoid(x[:,2])
      return torch.stack((steering,accceleartion,brake), dim=1)

model=DQN(state_size,action_size).to(device)
target_model=DQN(state_size, action_size).to(device)
target_model.load_state_dict(model.state_dict())
target_model.eval()


optimizer=optim.Adam(model.parameters(), lr=LEARNING_RATE)
loss_fn=nn.MSELoss()

def train():
  if not memory.can_sample(BATCH_SIZE):
    return

  states, actions, rewards, next_states,dones=memory.sample(BATCH_SIZE)
  with torch.no_grad():
    target_qs=target_model(next_states)
    max_future_q=torch.max(target_qs, dim=1)[0]
    new_qs=rewards+DISCOUNT*max_future_q
  current_qs=model(states)
  #current_qs=torch.gather(1, actions.unsqueeze(1)).squeeze(1)#need to fix this here since our action space is continuous(maybe just remove this?)

# Calculate losses for each action component
  loss_steering = loss_fn(current_qs[:, 0], new_qs[:, 0])  # Loss for steering
  loss_acceleration = loss_fn(current_qs[:, 1], new_qs[:, 1])  # Loss for acceleration
  loss_brake = loss_fn(current_qs[:, 2], new_qs[:, 2])  # Loss for braking

  # Total loss is the sum of individual losses
  loss = loss_steering + loss_acceleration + loss_brake

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  return loss.item()

state = env.reset()  # Shape: (NUM_ENVS, H, W, C)
state = torch.tensor(state.transpose((0, 3, 1, 2)), dtype=torch.float32, device=device) / 255.0



step=0
episode_rewards=[]
episode_lengths=[]
current_episode_reward=np.zeros(NUM_ENVS)
current_episode_length=np.zeros(NUM_ENVS)

while step<TOTAL_TIMESTEPS:
  if np.random.rand() < EPSILON:
    action=np.array([[np.random.uniform(-1,1),np.random.uniform(0,1),np.random.uniform(0,1)] for _ in range(NUM_ENVS)])
  else:
    with torch.no_grad():
      action=model(state).cpu().numpy()
  next_state,reward, done,_=env.step(action)
  next_state = torch.tensor(next_state.transpose((0, 3, 1, 2)), dtype=torch.float32, device=device) / 255.0
  for i in range(NUM_ENVS):
    memory.add((state[i].cpu().numpy(), action[i], reward[i], next_state[i].cpu().numpy(), done[i]))
    current_episode_reward[i]+=reward[i]
    current_episode_length[i]+=1
    if done[i]:
      episode_rewards.append(current_episode_reward[i])
      episode_lengths.append(current_episode_length[i])
      current_episode_reward[i]=0
      current_episode_length[i]=0
  state=next_state
  step+=NUM_ENVS
      # Train only after collecting enough data
  loss = None
  if step > TRAINING_START and step % 4 == 0:
      loss = train()
  if step % TARGET_UPDATE_FREQ==0:
    target_model.load_state_dict(model.state_dict())
  if EPSILON>EPSILON_MIN:
    EPSILON*=EPSILON_DECAY
  if step % 10000==0:
    avg_reward=np.mean(episode_rewards[-100:] if len(episode_rewards)>0 else 0)
    avg_length = np.mean(episode_lengths[-100:]) if len(episode_lengths) > 0 else 0
    last_loss = loss if loss is not None else 0

torch.save(model.state_dict(), "dqn_halminton_pytorch.pth")


IndexError: too many indices for tensor of dimension 1

In [19]:
#Deep Q network method
#IMPORTANT: in order to use Deep Q network method we need to  Discretize
#a continuous action space to use with DQN. this can be computationally expensive
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import deque
import random
import itertools

# Device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Hyperparameters
LEARNING_RATE = 0.001
DISCOUNT = 0.99
EPSILON = 1.0
EPSILON_DECAY = 0.995
EPSILON_MIN = 0.05
MEMORY_SIZE = 100000
BATCH_SIZE = 64
TARGET_UPDATE_FREQ = 1000
TOTAL_TIMESTEPS = 500000
TRAINING_START = 10000

# Action space discretization
NUM_BINS = 20  # Consider reducing to 10 for computational feasibility
STEERING_MIN, STEERING_MAX = -1.0, 1.0  # Define based on your environment
ACCELERATION_MIN, ACCELERATION_MAX = 0.0, 1.0
BRAKE_MIN, BRAKE_MAX = 0.0, 1.0

# Generate bins for each action component
steering_bins = np.linspace(STEERING_MIN, STEERING_MAX, NUM_BINS)
acceleration_bins = np.linspace(ACCELERATION_MIN, ACCELERATION_MAX, NUM_BINS)
brake_bins = np.linspace(BRAKE_MIN, BRAKE_MAX, NUM_BINS)

# Create all possible action combinations
action_combinations = list(itertools.product(range(NUM_BINS), repeat=3))  # (steering_bin, acceleration_bin, brake_bin)
NUM_ACTIONS = len(action_combinations)  # 20^3 = 8000

# Precompute action vectors for each discrete action
def get_action_vector(action_index):
    steering_idx, acceleration_idx, brake_idx = action_combinations[action_index]
    steering = steering_bins[steering_idx]
    acceleration = acceleration_bins[acceleration_idx]
    brake = brake_bins[brake_idx]
    return np.array([steering, acceleration, brake])

# Replay Buffer
class ReplayBuffer:
    def __init__(self, size):
        self.buffer = deque(maxlen=size)

    def add(self, experience):
        self.buffer.append(experience)

    def sample(self, batch_size):
        batch = random.sample(self.buffer, batch_size)
        states, actions, rewards, next_states, dones = zip(*batch)
        return (
            torch.tensor(np.array(states), dtype=torch.float32, device=device),
            torch.tensor(actions, dtype=torch.long, device=device).unsqueeze(1),  # Actions as indices
            torch.tensor(rewards, dtype=torch.float32, device=device).unsqueeze(1),
            torch.tensor(np.array(next_states), dtype=torch.float32, device=device),
            torch.tensor(dones, dtype=torch.float32, device=device).unsqueeze(1),
        )

    def can_sample(self, batch_size):
        return len(self.buffer) >= batch_size

memory = ReplayBuffer(MEMORY_SIZE)

# Q-network
class DQN(nn.Module):
    def __init__(self, state_size, action_size):
        super(DQN, self).__init__()
        self.network = nn.Sequential(
            # Convolutional layers
            nn.Conv2d(in_channels=3, out_channels=32, kernel_size=5, stride=2, padding=2),  # Output: (32, 24, 24)
            nn.ReLU(),
            nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, stride=2, padding=1),  # Output: (64, 12, 12)
            nn.ReLU(),
            nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, stride=2, padding=1),  # Output: (128, 6, 6)
            nn.ReLU(),
            nn.BatchNorm2d(128),
            nn.MaxPool2d(kernel_size=3, stride=2, padding=1),  # Output: (128, 3, 3)
            nn.Flatten(),
            nn.Linear(3 * 3 * 128, 512),  # Updated from 6*6*128 to 3*3*128
            nn.ReLU(),
            nn.Linear(512, action_size)  # Output layer for Q-values
        )

    def forward(self, x):
        return self.network(x)  # Shape: (batch_size, NUM_ACTIONS)

# Initialize networks
state_size = (3, 48, 48)  # Example state size, adjust based on your environment
action_size = NUM_ACTIONS

model = DQN(state_size, action_size).to(device)
target_model = DQN(state_size, action_size).to(device)
target_model.load_state_dict(model.state_dict())
target_model.eval()

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
loss_fn = nn.MSELoss()

# Training function
def train_step():
    if not memory.can_sample(BATCH_SIZE):
        return None

    states, actions, rewards, next_states, dones = memory.sample(BATCH_SIZE)

    # Current Q-values
    current_qs = model(states).gather(1, actions)  # Shape: (batch_size, 1)

    with torch.no_grad():
        # Next Q-values from target network
        next_qs = target_model(next_states)
        max_next_qs, _ = torch.max(next_qs, dim=1, keepdim=True)  # Shape: (batch_size, 1)
        target_qs = rewards + DISCOUNT * max_next_qs * (1 - dones)  # Shape: (batch_size, 1)

    # Compute loss
    loss = loss_fn(current_qs, target_qs)

    # Optimize the model
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    return loss.item()

# Initialize environment (replace with your actual environment)
class DummyEnv:
    def __init__(self, num_envs, state_shape):
        self.num_envs = num_envs
        self.state_shape = state_shape

    def reset(self):
        return np.random.randint(0, 255, size=(self.num_envs, *self.state_shape)).astype(np.uint8)

    def step(self, actions):
        next_state = np.random.randint(0, 255, size=(self.num_envs, *self.state_shape)).astype(np.uint8)
        reward = np.random.rand(self.num_envs)
        done = np.random.choice([False, True], size=self.num_envs, p=[0.95, 0.05])
        info = {}
        return next_state, reward, done, info

# Example parameters, adjust based on your environment
NUM_ENVS = 4
env = DummyEnv(NUM_ENVS, (48, 48, 3))

# Initialize state
state = env.reset()  # Shape: (NUM_ENVS, H, W, C)
state = torch.tensor(state.transpose((0, 3, 1, 2)), dtype=torch.float32, device=device) / 255.0

step = 0
episode_rewards = []
episode_lengths = []
current_episode_reward = np.zeros(NUM_ENVS)
current_episode_length = np.zeros(NUM_ENVS)

while step < TOTAL_TIMESTEPS:
    if np.random.rand() < EPSILON:
        # Select random discrete action indices
        action_indices = np.random.randint(0, NUM_ACTIONS, size=NUM_ENVS)
        action_vectors = np.array([get_action_vector(idx) for idx in action_indices])
    else:
        with torch.no_grad():
            qs = model(state)  # Shape: (NUM_ENVS, NUM_ACTIONS)
            action_indices = qs.argmax(dim=1).cpu().numpy()
            action_vectors = np.array([get_action_vector(idx) for idx in action_indices])

    # Execute actions in the environment
    next_state, reward, done, _ = env.step(action_vectors)
    next_state = torch.tensor(next_state.transpose((0, 3, 1, 2)), dtype=torch.float32, device=device) / 255.0

    for i in range(NUM_ENVS):
        memory.add((
            state[i].cpu().numpy(),
            action_indices[i],
            reward[i],
            next_state[i].cpu().numpy(),
            done[i]
        ))
        current_episode_reward[i] += reward[i]
        current_episode_length[i] += 1
        if done[i]:
            episode_rewards.append(current_episode_reward[i])
            episode_lengths.append(current_episode_length[i])
            current_episode_reward[i] = 0
            current_episode_length[i] = 0

    state = next_state
    step += NUM_ENVS

    # Train only after collecting enough data
    loss = None
    if step > TRAINING_START and step % 4 == 0:
        loss = train_step()

    # Update target network
    if step % TARGET_UPDATE_FREQ == 0:
        target_model.load_state_dict(model.state_dict())

    # Decay epsilon
    if EPSILON > EPSILON_MIN:
        EPSILON *= EPSILON_DECAY
        EPSILON = max(EPSILON, EPSILON_MIN)

    # Logging
    if step % 10000 == 0:
        if len(episode_rewards) >= 100:
            avg_reward = np.mean(episode_rewards[-100:])
            avg_length = np.mean(episode_lengths[-100:])
        else:
            avg_reward = np.mean(episode_rewards) if len(episode_rewards) > 0 else 0
            avg_length = np.mean(episode_lengths) if len(episode_lengths) > 0 else 0
        last_loss = loss if loss is not None else 0
        print(f"Step: {step}, Avg Reward: {avg_reward:.2f}, Avg Length: {avg_length:.2f}, Loss: {last_loss:.4f}, Epsilon: {EPSILON:.4f}")

# Save the trained model
torch.save(model.state_dict(), "dqn_halminton_pytorch_discrete.pth")


Step: 10000, Avg Reward: 8.71, Avg Length: 17.42, Loss: 0.0000, Epsilon: 0.0500
Step: 20000, Avg Reward: 9.61, Avg Length: 19.50, Loss: 194.5361, Epsilon: 0.0500
Step: 30000, Avg Reward: 12.33, Avg Length: 24.42, Loss: 15576.6113, Epsilon: 0.0500
Step: 40000, Avg Reward: 11.57, Avg Length: 23.16, Loss: 116322.4922, Epsilon: 0.0500
Step: 50000, Avg Reward: 8.91, Avg Length: 17.94, Loss: 1943068.2500, Epsilon: 0.0500
Step: 60000, Avg Reward: 9.20, Avg Length: 18.39, Loss: 33074010.0000, Epsilon: 0.0500
Step: 70000, Avg Reward: 9.40, Avg Length: 19.08, Loss: 205881312.0000, Epsilon: 0.0500
Step: 80000, Avg Reward: 10.63, Avg Length: 21.49, Loss: 1109689216.0000, Epsilon: 0.0500
Step: 90000, Avg Reward: 10.38, Avg Length: 20.29, Loss: 4193675264.0000, Epsilon: 0.0500
Step: 100000, Avg Reward: 9.55, Avg Length: 18.99, Loss: 20565917696.0000, Epsilon: 0.0500
Step: 110000, Avg Reward: 10.98, Avg Length: 21.63, Loss: 29073852416.0000, Epsilon: 0.0500
Step: 120000, Avg Reward: 8.54, Avg Length:

KeyboardInterrupt: 

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import deque
import random
import copy

# Device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Hyperparameters
LEARNING_RATE_ACTOR = 1e-4
LEARNING_RATE_CRITIC = 1e-3
DISCOUNT = 0.99
TAU = 0.005  # For soft updates
MEMORY_SIZE = 100000
BATCH_SIZE = 64
TOTAL_TIMESTEPS = 500000
TRAINING_START = 10000
NOISE_STD = 0.2
NOISE_DECAY = 0.9995
NOISE_MIN = 0.05

# Environment parameters (adjust based on your actual environment)
NUM_ENVS = 4
STATE_SHAPE = (3, 48, 48)  # (C, H, W)
ACTION_DIM = 3  # Steering, Acceleration, Brake
ACTION_LIMITS = np.array([1.0, 1.0, 1.0])  # [steering, acceleration, brake]

# Replay Buffer
class ReplayBuffer:
    def __init__(self, size):
        self.buffer = deque(maxlen=size)

    def add(self, experience):
        self.buffer.append(experience)

    def sample(self, batch_size):
        batch = random.sample(self.buffer, batch_size)
        states, actions, rewards, next_states, dones = zip(*batch)
        return (
            torch.tensor(np.array(states), dtype=torch.float32, device=device),
            torch.tensor(np.array(actions), dtype=torch.float32, device=device),
            torch.tensor(rewards, dtype=torch.float32, device=device).unsqueeze(1),
            torch.tensor(np.array(next_states), dtype=torch.float32, device=device),
            torch.tensor(dones, dtype=torch.float32, device=device).unsqueeze(1),
        )

    def can_sample(self, batch_size):
        return len(self.buffer) >= batch_size

memory = ReplayBuffer(MEMORY_SIZE)

# Ornstein-Uhlenbeck Noise for exploration
class OUNoise:
    def __init__(self, action_dim, std=0.2, theta=0.15, dt=1e-2, x0=None):
        self.action_dim = action_dim
        self.theta = theta
        self.std = std
        self.dt = dt
        self.x0 = x0
        self.reset()

    def reset(self):
        self.x = self.x0 if self.x0 is not None else np.zeros(self.action_dim)

    def sample(self):
        dx = self.theta * (-self.x) * self.dt + self.std * np.sqrt(self.dt) * np.random.normal(size=self.action_dim)
        self.x += dx
        return self.x

noise = OUNoise(action_dim=ACTION_DIM, std=NOISE_STD)

# Actor Network with Separate Scaling
class Actor(nn.Module):
    def __init__(self, state_size, action_dim, action_limits):
        super(Actor, self).__init__()
        self.steering_limit = torch.tensor(action_limits[0], dtype=torch.float32, device=device)
        self.acceleration_limit = torch.tensor(action_limits[1], dtype=torch.float32, device=device)
        self.brake_limit = torch.tensor(action_limits[2], dtype=torch.float32, device=device)

        self.network = nn.Sequential(
            nn.Conv2d(in_channels=state_size[0], out_channels=32, kernel_size=5, stride=2, padding=2),  # (32, 24, 24)
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=3, stride=2, padding=1),  # (64, 12, 12)
            nn.ReLU(),
            nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1),  # (128, 6, 6)
            nn.ReLU(),
            nn.BatchNorm2d(128),
            nn.MaxPool2d(kernel_size=3, stride=2, padding=1),  # (128, 3, 3)
            nn.Flatten(),
            nn.Linear(128 * 3 * 3, 512),
            nn.ReLU(),
            nn.Linear(512, action_dim)
        )

    def forward(self, x):
        x = self.network(x)  # Shape: (batch_size, action_dim)

        # Split the output for each action component
        steering = torch.tanh(x[:, 0]) * self.steering_limit  # [-1, 1]
        acceleration = torch.sigmoid(x[:, 1]) * self.acceleration_limit  # [0, 1]
        brake = torch.sigmoid(x[:, 2]) * self.brake_limit  # [0, 1]

        # Combine the action components
        return torch.stack([steering, acceleration, brake], dim=1)  # Shape: (batch_size, 3)

# Critic Network
class Critic(nn.Module):
    def __init__(self, state_size, action_dim):
        super(Critic, self).__init__()
        # State pathway
        self.state_network = nn.Sequential(
            nn.Conv2d(in_channels=state_size[0], out_channels=32, kernel_size=5, stride=2, padding=2),  # (32, 24, 24)
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=3, stride=2, padding=1),  # (64, 12, 12)
            nn.ReLU(),
            nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1),  # (128, 6, 6)
            nn.ReLU(),
            nn.BatchNorm2d(128),
            nn.MaxPool2d(kernel_size=3, stride=2, padding=1),  # (128, 3, 3)
            nn.Flatten(),
            nn.Linear(128 * 3 * 3, 512),
            nn.ReLU()
        )
        # Action pathway
        self.action_network = nn.Sequential(
            nn.Linear(action_dim, 512),
            nn.ReLU()
        )
        # Combined pathway
        self.combined_network = nn.Sequential(
            nn.Linear(512 + 512, 512),
            nn.ReLU(),
            nn.Linear(512, 1)  # Output Q-value
        )

    def forward(self, state, action):
        state_out = self.state_network(state)  # (batch_size, 512)
        action_out = self.action_network(action)  # (batch_size, 512)
        combined = torch.cat([state_out, action_out], dim=1)  # (batch_size, 1024)
        q_value = self.combined_network(combined)  # (batch_size, 1)
        return q_value

# Initialize Actor and Critic networks
state_size = STATE_SHAPE
actor = Actor(state_size, ACTION_DIM, ACTION_LIMITS).to(device)
actor_target = copy.deepcopy(actor).to(device)
actor_target.eval()

critic = Critic(state_size, ACTION_DIM).to(device)
critic_target = copy.deepcopy(critic).to(device)
critic_target.eval()

# Optimizers
actor_optimizer = optim.Adam(actor.parameters(), lr=LEARNING_RATE_ACTOR)
critic_optimizer = optim.Adam(critic.parameters(), lr=LEARNING_RATE_CRITIC)

# Loss function
critic_loss_fn = nn.MSELoss()

# Soft update function
def soft_update(target, source, tau):
    for target_param, source_param in zip(target.parameters(), source.parameters()):
        target_param.data.copy_(tau * source_param.data + (1.0 - tau) * target_param.data)

# Training function
def train_step():
    if not memory.can_sample(BATCH_SIZE):
        return None, None

    states, actions, rewards, next_states, dones = memory.sample(BATCH_SIZE)

    # -------------------- Critic Update -------------------- #
    with torch.no_grad():
        # Get target actions from target actor
        target_actions = actor_target(next_states)
        # Get target Q-values from target critic
        target_qs = critic_target(next_states, target_actions)
        # Compute y = r + gamma * Q'(s', a')
        y = rewards + DISCOUNT * target_qs * (1 - dones)

    # Get current Q-values from critic
    current_qs = critic(states, actions)

    # Compute critic loss
    critic_loss = critic_loss_fn(current_qs, y)

    # Optimize Critic
    critic_optimizer.zero_grad()
    critic_loss.backward()
    # Optionally, clip gradients to prevent exploding gradients
    torch.nn.utils.clip_grad_norm_(critic.parameters(), max_norm=1.0)
    critic_optimizer.step()

    # -------------------- Actor Update -------------------- #
    # Get actions from current actor
    current_actions = actor(states)
    # Compute actor loss (maximize Q-values)
    actor_loss = -critic(states, current_actions).mean()

    # Optimize Actor
    actor_optimizer.zero_grad()
    actor_loss.backward()
    # Optionally, clip gradients
    torch.nn.utils.clip_grad_norm_(actor.parameters(), max_norm=1.0)
    actor_optimizer.step()

    # -------------------- Soft Update Targets -------------------- #
    soft_update(actor_target, actor, TAU)
    soft_update(critic_target, critic, TAU)

    return critic_loss.item(), actor_loss.item()

# Initialize environment (replace DummyEnv with your actual environment)
class DummyEnv:
    def __init__(self, num_envs, state_shape):
        self.num_envs = num_envs
        self.state_shape = state_shape

    def reset(self):
        # Returns (num_envs, C, H, W)
        return np.random.randint(0, 255, size=(self.num_envs, *self.state_shape)).astype(np.uint8)

    def step(self, actions):
        # actions: numpy array of shape (num_envs, action_dim)
        # Here, actions are already scaled to the appropriate ranges
        next_state = np.random.randint(0, 255, size=(self.num_envs, *self.state_shape)).astype(np.uint8)
        reward = np.random.rand(self.num_envs)
        done = np.random.choice([False, True], size=self.num_envs, p=[0.95, 0.05])
        info = {}
        return next_state, reward, done, info

# Initialize environment
env = DummyEnv(NUM_ENVS, STATE_SHAPE)

# Initialize state
state = env.reset()  # Shape: (NUM_ENVS, C, H, W)
state = torch.tensor(state, dtype=torch.float32, device=device) / 255.0

# Initialize loss variables
critic_loss, actor_loss = None, None  # Initialize before the loop

step = 0
episode_rewards = []
episode_lengths = []
current_episode_reward = np.zeros(NUM_ENVS)
current_episode_length = np.zeros(NUM_ENVS)

while step < TOTAL_TIMESTEPS:
    if step < TRAINING_START:
        # Exploration: Select random actions within action limits
        # Steering: [-1, 1], Acceleration: [0, 1], Brake: [0, 1]
        steering = np.random.uniform(low=-ACTION_LIMITS[0], high=ACTION_LIMITS[0], size=(NUM_ENVS, 1))
        acceleration = np.random.uniform(low=0, high=ACTION_LIMITS[1], size=(NUM_ENVS, 1))
        brake = np.random.uniform(low=0, high=ACTION_LIMITS[2], size=(NUM_ENVS, 1))
        action_vectors = np.hstack([steering, acceleration, brake])
    else:
        # Select actions using the actor network
        with torch.no_grad():
            action = actor(state).cpu().numpy()
        # Add exploration noise
        noise_sample = noise.sample()
        action_vectors = action + noise_sample
        # Clip actions to be within action limits
        action_vectors[:,0] = np.clip(action_vectors[:,0], -ACTION_LIMITS[0], ACTION_LIMITS[0])  # Steering
        action_vectors[:,1] = np.clip(action_vectors[:,1], 0, ACTION_LIMITS[1])  # Acceleration
        action_vectors[:,2] = np.clip(action_vectors[:,2], 0, ACTION_LIMITS[2])  # Brake

    # Execute actions in the environment
    next_state, reward, done, _ = env.step(action_vectors)
    next_state = torch.tensor(next_state, dtype=torch.float32, device=device) / 255.0

    for i in range(NUM_ENVS):
        memory.add((
            state[i].cpu().numpy(),
            action_vectors[i],
            reward[i],
            next_state[i].cpu().numpy(),
            done[i]
        ))
        current_episode_reward[i] += reward[i]
        current_episode_length[i] += 1
        if done[i]:
            episode_rewards.append(current_episode_reward[i])
            episode_lengths.append(current_episode_length[i])
            current_episode_reward[i] = 0
            current_episode_length[i] = 0

    state = next_state
    step += NUM_ENVS

    # Train the agent
    if step > TRAINING_START and step % 4 == 0:
        critic_loss, actor_loss = train_step()

    # Decay noise standard deviation
    if step > TRAINING_START:
        noise.std = max(noise.std * NOISE_DECAY, NOISE_MIN)

    # Logging
    if step % 10000 == 0:
        if len(episode_rewards) >= 100:
            avg_reward = np.mean(episode_rewards[-100:])
            avg_length = np.mean(episode_lengths[-100:])
        else:
            avg_reward = np.mean(episode_rewards) if len(episode_rewards) > 0 else 0
            avg_length = np.mean(episode_lengths) if len(episode_lengths) > 0 else 0
        last_critic_loss = critic_loss if critic_loss is not None else 0
        last_actor_loss = actor_loss if actor_loss is not None else 0
        print(f"Step: {step}, Avg Reward: {avg_reward:.2f}, Avg Length: {avg_length:.2f}, Critic Loss: {last_critic_loss:.4f}, Actor Loss: {last_actor_loss:.4f}, Noise Std: {noise.std:.4f}")

    # Optionally, save the model periodically
    if step % 100000 == 0:
        torch.save({
            'actor_state_dict': actor.state_dict(),
            'critic_state_dict': critic.state_dict(),
            'actor_target_state_dict': actor_target.state_dict(),
            'critic_target_state_dict': critic_target.state_dict(),
            'actor_optimizer_state_dict': actor_optimizer.state_dict(),
            'critic_optimizer_state_dict': critic_optimizer.state_dict(),
            'noise_std': noise.std,
        }, f"ddpg_halminton_pytorch_step_{step}.pth")

# Save the final model
torch.save({
    'actor_state_dict': actor.state_dict(),
    'critic_state_dict': critic.state_dict(),
    'actor_target_state_dict': actor_target.state_dict(),
    'critic_target_state_dict': critic_target.state_dict(),
    'actor_optimizer_state_dict': actor_optimizer.state_dict(),
    'critic_optimizer_state_dict': critic_optimizer.state_dict(),
    'noise_std': noise.std,
}, "ddpg_halminton_pytorch_final.pth")


Step: 10000, Avg Reward: 9.02, Avg Length: 18.26, Critic Loss: 0.0000, Actor Loss: 0.0000, Noise Std: 0.2000
Step: 20000, Avg Reward: 11.48, Avg Length: 22.77, Critic Loss: 0.1274, Actor Loss: -2.7638, Noise Std: 0.0573
Step: 30000, Avg Reward: 10.44, Avg Length: 21.05, Critic Loss: 0.4598, Actor Loss: -4.5441, Noise Std: 0.0500
